# ?????
server.port=8081
server.servlet.context-path=/

# JSP ??
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# ????????
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ????
logging.level.org.example=INFO
logging.level.org.springframework.web=INFO
